### ISSUE TITLE
loggin system not working

### ISSUE THREAD

**Issue by bitworkz** [Urigo/Ionic2CLI-Meteor-WhatsApp#103]
when i finish step 7 for user authentication i get the following error:
meteor_1.Meteor.loggingIn is not a function

stack:
TypeError: meteor_1.Meteor.loggingIn is not a function
    at SafeSubscriber._next (http://localhost:8100/build/main.js:205309:29)
    at SafeSubscriber.__tryOrSetError (http://localhost:8100/build/main.js:20091:16)
    at SafeSubscriber.next (http://localhost:8100/build/main.js:20031:27)
    at Subscriber._next (http://localhost:8100/build/main.js:19969:26)
    at Subscriber.next (http://localhost:8100/build/main.js:19933:18)
    at http://localhost:8100/build/main.js:190955:77
    at Array.forEach (native)
    at http://localhost:8100/build/main.js:190955:31
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9283)
    at r.run (http://localhost:8100/build/polyfills.js:3:4452)

**Comment by bitworkz** [comment]
it seems to work now.
