### ISSUE TITLE
Runtime Error Package is not defined

### ISSUE THREAD

**Issue by kenpachi-zaraki** [Urigo/Ionic2CLI-Meteor-WhatsApp#105]
Hi,

I've cloned the repository: 
git clone https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp

I've already been through the issue:
https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/70
, but once it has been fixed, I'm now getting the following error when I launch the whatsapp app (http://localhost:8100/):

**Runtime Error
Package is not defined**

Stack
ReferenceError: Package is not defined
    at Object.defineProperty.value (http://localhost:8100/build/main.js:42098:18)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.<anonymous> (http://localhost:8100/build/main.js:174817:16)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at Object.defineProperty.value (http://localhost:8100/build/main.js:66:18)
    at http://localhost:8100/build/main.js:69:10

_Ionic Framework: 3.3.0
Ionic App Scripts: 1.3.7
Angular Core: 4.1.2
Angular Compiler CLI: 4.1.2
Node: 6.11.0
OS Platform: Linux 4.4
Navigator Platform: Win32
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36_

Can you please help?

**Comment by KevinMarzec** [comment]
I'm getting the same issue - did you ever figure this out?

**Comment by kenpachi-zaraki** [comment]
Hi,

Cloning the repo and installing the packages and then launching ionic serve won't directly work.

There are several steps throughout the 18 chapters (where for example you need to create symbolic links) that need to be carried out for it to work.

If you start from scratch and you go through all the 18 chapters of the tutorial, it will surely work.

@Urigo , an easier way would be to list all those required steps in the README.md of the github repo for the ionic serve command to work.

Kind regards.
KenChan

**Comment by pkitatta** [comment]
Hi, did you get through step 8? I get this error: 

 Type 'Observable<Chat[]>' is not assignable to type 'Observable<Chat[]>'. Two different types with this name
            exist, but they are unrelated. Property 'source' is protected but type 'Observable<T>' is not a class
            derived from 'Observable<T>'.
similar to this:
https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/56

**Comment by kenpachi-zaraki** [comment]
Hi,
Please check your imports.

I did not encounter such problem. Step 8 worked fine for me.

**Comment by airstep** [comment]
In root tsconfig.json I've added:

`
    "paths": {
      "api/*": ["./api/server/*"],
      "rxjs": ["node_modules/rxjs"]
    },
`

this issue bcz of two node_modules folders linked at the server and real on the client

**Comment by pkitatta** [comment]
O.K. am officially confused; I restarted building the app from scratch and this time I didn't get this error. WHY! I spent days last time trying to come up with a solution until I found that one above. This time I wanted to try the last two but am getting no error at this stage like before.

**Comment by pkitatta** [comment]
O.K. I initially got a solution on #56 .

 But now am officially confused; I restarted building the app from scratch and this time I didn't get this error. WHY! I spent days last time trying to come up with a solution until I found that one above. This time I wanted to try the last two but am getting no error at this stage like before.

**Comment by darkbasic** [comment]
Closing due to inactivity and cleanup after tons of new updates.
Feel free to open a new issue if you are still affected.
