### ISSUE TITLE
--prod builds fail

### ISSUE THREAD

**Issue by jakobwilkenson** [Urigo/Ionic2CLI-Meteor-WhatsApp#157]
After downloading the current version of the sample app and running npm run build --prod it fails with the below output (just running npm run build works).

    [18:32:00]  ionic-app-scripts 3.0.0 
    [18:32:00]  build prod started ... 
    [18:32:00]  clean started ... 
    [18:32:00]  clean finished in 1 ms 
    [18:32:00]  copy started ... 
    [18:32:00]  deeplinks started ... 
    [18:32:00]  deeplinks finished in 81 ms 
    [18:32:00]  ngc started ... 
    [18:32:06]  ngc finished in 6.17 s 
    [18:32:06]  preprocess started ... 
    [18:32:06]  copy finished in 6.29 s 
    [18:32:06]  preprocess finished in 72 ms 
    [18:32:06]  webpack started ... 
    [18:32:28]  ionic-app-script task: "build" 
    [18:32:28]  Error: ./api/server/collections/index.ts Module build failed: Error: ENOENT: no such file or directory, open 
                '/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/api/server/collections/index.js' @ 
                ./src/pages/profile/profile.ts 10:20-46 @ ./src/pages/login/facebook.ts @ 
                ./src/pages/verification/verification.ts @ ./src/pages/login/login.ts @ ./src/app/app.component.ts @ 
                ./src/app/app.module.ngfactory.ts @ ./src/app/main.ts,./api/server/models.ts Module build failed: Error: 
                ENOENT: no such file or directory, open 
                '/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/api/server/models.js' @ 
                ./src/services/phone.ts 129:15-36 @ ./src/app/app.module.ngfactory.ts @ 
                ./src/app/main.ts,./node_modules/meteor-client.js Module build failed: TypeError: Cannot read property 
                'kind' of undefined at Object.isFunctionExpression 
                (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:10780:21)
                at isJavaScriptConstructor 
                (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:37601:58)
                at getJavaScriptClassType 
                (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:37611:17)
                at checkCallExpression 
                (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:37660:46)
                at checkExpressionWorker 
                (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:39139:28)
                at checkExpression 
                (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:39077:42)
                at checkBinaryLikeExpression 
                (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:38657:29)
                at checkBinaryExpression 
                (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:38649:20)
                at checkExpressionWorker 
                (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:39169:28)
                at checkExpression 
                (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:39077:42)
                @ ./src/app/main.ts 3:0-24 
    Error: ./api/server/collections/index.ts
    Module build failed: Error: ENOENT: no such file or directory, open '/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/api/server/collections/index.js'
    @ ./src/pages/profile/profile.ts 10:20-46
    @ ./src/pages/login/facebook.ts
    @ ./src/pages/verification/verification.ts
    @ ./src/pages/login/login.ts
    @ ./src/app/app.component.ts
    @ ./src/app/app.module.ngfactory.ts
    @ ./src/app/main.ts,./api/server/models.ts
    Module build failed: Error: ENOENT: no such file or directory, open '/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/api/server/models.js'
    @ ./src/services/phone.ts 129:15-36
    @ ./src/app/app.module.ngfactory.ts
    @ ./src/app/main.ts,./node_modules/meteor-client.js
    Module build failed: TypeError: Cannot read property 'kind' of undefined
        at Object.isFunctionExpression (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:10780:21)
        at isJavaScriptConstructor (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:37601:58)
        at getJavaScriptClassType (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:37611:17)
        at checkCallExpression (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:37660:46)
        at checkExpressionWorker (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:39139:28)
        at checkExpression (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:39077:42)
        at checkBinaryLikeExpression (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:38657:29)
        at checkBinaryExpression (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:38649:20)
        at checkExpressionWorker (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:39169:28)
        at checkExpression (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/typescript/lib/typescript.js:39077:42)
    @ ./src/app/main.ts 3:0-24
        at new BuildError (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/@ionic/app-scripts/dist/util/errors.js:16:28)
        at callback (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/@ionic/app-scripts/dist/webpack.js:123:28)
        at emitRecords.err (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/webpack/lib/Compiler.js:269:13)
        at Compiler.emitRecords (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/webpack/lib/Compiler.js:375:38)
        at emitAssets.err (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/webpack/lib/Compiler.js:262:10)
        at applyPluginsAsyncSeries1.err (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/webpack/lib/Compiler.js:368:12)
        at next (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/tapable/lib/Tapable.js:218:11)
        at Compiler.compiler.plugin (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
        at Compiler.applyPluginsAsyncSeries1 (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/tapable/lib/Tapable.js:222:13)
        at Compiler.afterEmit (/Users/jakobwilkenson/Projects/research/Ionic2CLI-Meteor-WhatsApp-master/node_modules/webpack/lib/Compiler.js:365:9)
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! whatsapp@0.0.1 build: `ionic-app-scripts build`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the whatsapp@0.0.1 build script.
    npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

My Ionic Info:
cli packages: (/usr/local/lib/node_modules)

    @ionic/cli-utils  : 1.15.2
    ionic (Ionic CLI) : 3.15.2

global packages:

    cordova (Cordova CLI) : 7.0.1 

local packages:

    @ionic/app-scripts : 3.0.0
    Cordova Platforms  : android 6.3.0
    Ionic Framework    : ionic-angular 3.7.1

System:

    Android SDK Tools : 25.2.5
    ios-deploy        : 1.9.2 
    Node              : v8.7.0
    npm               : 5.5.1 
    OS                : macOS Sierra
    Xcode             : Xcode 9.0.1 Build version 9A1004 

Misc:

    backend : pro

**Comment by darkbasic** [comment]
Unfortunately the current tutorial has not been tested with AOT, but I'm already working on the new one where AOT will be tested since the beginning.

**Comment by darkbasic** [comment]
Let's track it here: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/113
