### ISSUE TITLE
ionic build errors

### ISSUE THREAD

**Issue by paduchurikowsik** [Urigo/Ionic2CLI-Meteor-WhatsApp#17]
Hi 
Thanks for the tutorials they helped me a lot and i was able integrate meteor in my ionic 2 app, and i was able to deploy the sever to AWS. Every thing is working good when i do 'ionic serve' but when i do 'ionic build' or 'ionic run android' it shows error saying that the

"Cannot find name 'Message' on line ......" [where i used public thisMessage: Message] 
but i import from api/model/whatsapp.d.ts in my 
src/pages/Message/Message.ts in ionic root

![capture](https://cloud.githubusercontent.com/assets/5306162/20114706/4e4382ea-a5c3-11e6-8aa3-a7bd6f065cf3.JPG)
![capture1](https://cloud.githubusercontent.com/assets/5306162/20114707/4e4410f2-a5c3-11e6-9a03-a928869a47ba.JPG)

Steps Followed"
1. Downloaded zip and extracted it
2. "npm install --save" on root folder
3. "meteor npm install --save" inside api folder
4. "meteor" inside api folder
5. "ionic build" on root of ionic folder

**Comment by AwsmOli** [comment]
I have the same thing,
It seems that Typscript resolves the whatsapp.model with the `declate module '*'` in `src/declarations.d.ts`  (if you mouse over it in VS Code or user CMD+Click on it it jumps to that file)

If you remove `declare module '*'` VS Code seems to be able to resolve the wright file, and `ionic serve` works fine, but on `ionic run android|ios` ngc failes with:
```
[09:49:46]  Error: Error at /Users/awli/Projects/test/.tmp/pages/messages/messages.ts:3:31 
[09:49:46]  File '/Users/awli/Projects/test/api/models/whatsapp.models.d.ts' is not a module. 
[09:49:46]  Error at /Users/awli/Projects/test/.tmp/pages/chats/chats.ts:4:22 
[09:49:46]  File '/Users/awli/Projects/test/api/models/whatsapp.models.d.ts' is not a module. 
[09:49:46]  Error at /Users/awli/Projects/test/.tmp/pages/chats/chats.ngfactory.ts:406:29 
[09:49:46]  Supplied parameters do not match any signature of call target. 
[09:49:46]  Error at /Users/awli/Projects/test/.tmp/pages/messages/messages.ngfactory.ts:518:90 
[09:49:46]  Property 'messages' is private and only accessible within class 'MessagesPage'. 
[09:49:46]  Error at /Users/awli/Projects/test/.tmp/pages/messages/messages.ngfactory.ts:523:41 
[09:49:46]  Property 'message' is private and only accessible within class 'MessagesPage'. 
[09:49:46]  Error at /Users/awli/Projects/test/.tmp/pages/messages/messages.ngfactory.ts:531:41 
[09:49:46]  Property 'message' is private and only accessible within class 'MessagesPage'. 
[09:49:46]  Error at /Users/awli/Projects/test/.tmp/pages/messages/messages.ngfactory.ts:534:46 
[09:49:46]  Property 'message' is private and only accessible within class 'MessagesPage'. 
[09:49:46]  Error at /Users/awli/Projects/test/.tmp/pages/messages/messages.ngfactory.ts:580:40 
[09:49:46]  Property 'picture' is private and only accessible within class 'MessagesPage'. 
[09:49:46]  Error at /Users/awli/Projects/test/.tmp/pages/messages/messages.ngfactory.ts:585:65 
[09:49:46]  Property 'title' is private and only accessible within class 'MessagesPage'. 
[09:49:46]  Error at /Users/awli/Projects/test/.tmp/pages/messages/messages.ngfactory.ts:663:43 
[09:49:46]  Property 'message' is private and only accessible within class 'MessagesPage'. 
[09:49:46]  ngc failed 
[09:49:46]  ionic-app-script task: "build" 
[09:49:46]  Error: Error 
```

I also found this issue, which seems to be related, but could not yet figure out how to make it work:
https://github.com/Microsoft/TypeScript/issues/9229

Got anyone any ideas?

**Comment by DAB0mB** [comment]
@paduchurikowsik I'm working on a fix right now should be rebased soon

**Comment by DAB0mB** [comment]
Should be deployed very soon :-)
Basically I turned all private data-members to public, updated webpack config and tsconfig, follow the upcoming changes.
