### ISSUE TITLE
Runtime Error of "meteor/accounts-base"

### ISSUE THREAD

**Issue by Ayesha17** [Urigo/Ionic2CLI-Meteor-WhatsApp#172]
After adding
 

> 
>   function requestPhoneVerification(phoneNumber: string, callback?: Function): void;
>       function verifyPhone(phoneNumber: string, code: string, callback?: Function): void;

      
in meteor.d.ts **runtime error of "meteor/accounts-base"** occur 

Error: Cannot find module "meteor/accounts-base"
    at webpackMissingModule (http://localhost:8100/build/main.js:548:87)
    at Object.214 (http://localhost:8100/build/main.js:548:184)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.151 (http://localhost:8100/build/main.js:65:15)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.685 (http://localhost:8100/build/main.js:1121:17)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.359 (http://localhost:8100/build/main.js:938:23)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.354 (http://localhost:8100/build/main.js:917:20)

**Comment by adelriosantiago** [comment]
Same here, any solution? It doesn't work even when using source at 7: https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/releases
