### ISSUE TITLE
Uncaught ReferenceError: __extends is not defined when run on device

### ISSUE THREAD

**Issue by AwsmOli** [Urigo/Ionic2CLI-Meteor-WhatsApp#18]
Hi,

Im getting an `Uncaught ReferenceError: __extends is not defined` when i try to run this on any device.

So i just cloned this Repo, and ran `npm i` which gave me:

```
npm WARN accounts-phone@0.0.1 requires a peer of meteor-client-side@~0.2.3 but none was installed.
npm WARN @angular/http@2.1.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN @angular/core@2.1.1 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN ionic-angular@2.0.0-rc.2 requires a peer of rxjs@5.0.0-beta.12 but none was installed.
npm WARN ionic-angular@2.0.0-rc.2 requires a peer of zone.js@0.6.21 but none was installed.
```

so i fixed the `package.json` and changed `meteor-client-side`, `rxjs` and `zone.js` to these versions:

```
    "meteor-client-side": "~0.2.3",
    "rxjs": "5.0.0-beta.12",
    "zone.js": "0.6.21"
```

than `npm i `ran fine.

next i ran `ionic serve` - and everything runs like a charm, but wen i try `ionic run android` on to a real device or` ionic run ios` on a simulator, i get a white screen and the following logs:

```
Uncaught ReferenceError: __extends is not defined
    at file:///android_asset/www/build/main.js:9:22535
    at file:///android_asset/www/build/main.js:9:24143
    at file:///android_asset/www/build/main.js:9:21256
    at Object.<anonymous> (file:///android_asset/www/build/main.js:9:21268)
    at Object.<anonymous> (file:///android_asset/www/build/main.js:9:27679)
    at e (file:///android_asset/www/build/main.js:1:101)
    at Object.<anonymous> (file:///android_asset/www/build/main.js:17:30095)
    at e (file:///android_asset/www/build/main.js:1:101)
    at Object.<anonymous> (file:///android_asset/www/build/main.js:16:5781)
    at e (file:///android_asset/www/build/main.js:1:101)
main.js:51 DEVICE READY FIRED AFTER 220 ms
```

Googeling the issue, i found another issue, in another repo: https://github.com/akveo/ng2-smart-table/issues/16

there they fixed it with adding`"noEmitHelpers": false` to the `tsconfig.json` but it didn't work out for me.

Can anyone confirm this?

**Comment by dotansimha** [comment]
Can you share your `webpack.config.js` file?

**Comment by AwsmOli** [comment]
Its the one from this repo: 

```
var path = require('path');
var webpack = require('webpack');

// for prod builds, we have already done AoT and AoT writes to disk
// so read the JS file from disk
// for dev buids, we actually want to pass in .ts files since we
// don't have .js files on disk, they're exclusively in memory

function getEntryPoint() {
  if (process.env.IONIC_ENV === 'prod') {
    return '{{TMP}}/app/main.prod.js';
  }
  return '{{TMP}}/app/main.dev.js';
}

function getPlugins() {
  if (process.env.IONIC_ENV === 'prod') {
    return [
      // This helps ensure the builds are consistent if source hasn't changed:
      new webpack.optimize.OccurrenceOrderPlugin(),
      // Try to dedupe duplicated modules, if any:
      // Add this back in when Angular fixes the issue: https://github.com/angular/angular-cli/issues/1587
      //new DedupePlugin()
    ];
  }
  return [
    new webpack.ProvidePlugin({
      __extends: 'typescript-extends'
    })
  ];
}

module.exports = {
  entry: getEntryPoint(),
  output: {
    path: '{{BUILD}}',
    filename: 'main.js'
  },

  resolve: {
    extensions: ['.js', '.json', '.ts'],
    alias: {
      'api': path.resolve(__dirname, '../api')
    }
  },

  module: {
    loaders: [
      {
        test: /\.json$/,
        loader: 'json'
      },
      {
        test: /\.ts$/,
        exclude: /(node_modules)/,
        loaders: ['awesome-typescript-loader']
      }
    ]
  },

  plugins: getPlugins(),

  // Some libraries import Node modules but don't use them in the browser.
  // Tell Webpack to provide empty mocks for them so importing them works.
  node: {
    fs: 'empty',
    net: 'empty',
    tls: 'empty',
    __dirname: true
  }
};
```

Literally only did the steps i mentioned :)

**Comment by dotansimha** [comment]
And did you `npm install typescript-extends` ?

**Comment by AwsmOli** [comment]
Just tried it, did not help.

**Comment by ekhmoi** [comment]
+1
The exact same problem

**Comment by metecantimur** [comment]
The exact same problem

**Comment by Urigo** [comment]
we are working on it, hopefully will be solved during the weekend

**Comment by ekhmoi** [comment]
Gracias! :)

**Comment by metecantimur** [comment]
# Findings

- Command **ionic build** sets **process.env.IONIC_ENV="prod"** in 
**config/webpack.config.js** 
in which case the following lines do not execute during the build process:
```
return [
    new webpack.ProvidePlugin({
      __extends: 'typescript-extends'
    })
  ];
```
which produces the error mentioned by @AwsmOli.

- During the build process, the source file **src/app/main.prod.ts** is compiled however this file seems to be incomplete.

**Comment by Urigo** [comment]
deployed the new fix from @DAB0mB  
Please check and made sure it works for you

**Comment by ekhmoi** [comment]
It Works !
Thank you!!!

**Comment by AwsmOli** [comment]
It works now, thanks :)
