### ISSUE TITLE
"meteor-client" not found

### ISSUE THREAD

**Issue by airstep** [Urigo/Ionic2CLI-Meteor-WhatsApp#185]
When I run command to generate client bundle and it's done execution I have a file meteor-client.js with size near 2Mb (last success time it was 4Mb) in node_modules.

Then I try to run project in debug mode and get:

Runtime Error
Cannot find module "meteor-client"
Stack
Error: Cannot find module "meteor-client"
    at Object.372 (http://localhost:8100/build/main.js:182:7)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at webpackJsonpCallback (http://localhost:8100/build/vendor.js:26:23)
    at http://localhost:8100/build/main.js:1:1

meteor version: 1.6.1.1
node --version: 9.11.1
npm --version: 5.6.0

If I create release version all works fine...

What did I forget to do? Where mistake is hidden?

**Comment by airstep** [comment]
Fixed when I switch to node 8.9.3 and reconfigure launch.json
