### ISSUE TITLE
@Babel/Runtime causes an error with webpack

### ISSUE THREAD

**Issue by rosunad** [Urigo/Ionic2CLI-Meteor-WhatsApp#190]
Following the tutorial (https://angular-meteor.com/tutorials/whatsapp2/ionic/setup) I'm facing a problem that I'm stuck with.

When I add at meteor server, the next time I run 'ionic serve' I get an error about webpack.

Meteor version 1.6.1.3.

This is the error that give me Meteor:

```
Error: The @babel/runtime npm package could not be found in your node_modules
W20180620-13:17:22.858(2)? (STDERR) directory. Please run the following command to install it:
W20180620-13:17:22.858(2)? (STDERR)
W20180620-13:17:22.858(2)? (STDERR)   meteor npm install --save @babel/runtime
```
After add , 'ionic serve' give me:

```
transpile started ...
There was an error in config file "/home/rosunad/projects/protocoloMeteor/webpack.config.js". Using defaults instead.
{ Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/rosunad/projects/protocoloMeteor/webpack.config.js:11:15)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3) code: 'MODULE_NOT_FOUND' }
[13:33:45]  typescript: node_modules/@types/meteor/mongo.d.ts, line: 49
            ';' expected.

      L48:  $all?: T[],
      L49:  $elemMatch?: T extends {} ? Query<T> : FieldExpression<T>,
      L50:  $size?: number,
```
I've created a Github repo, the last commit is just before you need to import

https://github.com/rosunad/protocoloMeteor

**Comment by rosunad** [comment]
Same as the resolved issue: https://github.com/Urigo/angular-meteor/issues/1924
