### ISSUE TITLE
App is Launched but can't pass the phone validation stage

### ISSUE THREAD

**Issue by DeeM297** [Urigo/Ionic2CLI-Meteor-WhatsApp#22]
Hi,

Just found about meteor through the ionic blog. It's a great tutorial and it's exciting to see what's possible to do. Thanks for sharing!

I'm trying to run the app and have done the following:
1) Launching the server from api folder with this command `meteor`
2) Launching the client from project root `ionic serve` 

Both are launched and getting this messages on the cmd prompt
1) _App running at: http://localhost:3000/_
2) _Running dev server:  http://localhost:8100_

The app is launched but I'm not able to pass the first phone validation screen. I'm inserting one of the admin phone number (+9721234567, +97212345678, +97212345679), I get the 'Confirm' alert but nothing happens when I click 'Yes'

Console shows the following message:
`polyfills.js:1 GET http://localhost:8100/sockjs/info?cb=id2fj7qgyy 404 (Not Found)`

Could this be a port issue because ionic app is running on http://localhost:8100 and meteor server is running on http://localhost:3000 ?
Any idea on how to solve this?

**Comment by metecantimur** [comment]
Hi, 
Your case seems to be same as mine #20

**Comment by DeeM297** [comment]
I think it could be the same problem. I am on Windows so can't try on an iOS emulator.

I tried to bypass phone and code verification validation but then I end up with the same 404 problem with later screens.

**Comment by nikhilcfc** [comment]
Same Issue for me as well.

**Comment by DeeM297** [comment]
When I launch meteor from the api folder, I am getting this output

```[[[[[ c:\Ionic2CLI-Meteor-WhatsApp\api ]]]]]

=> Started proxy.
collections/whatsapp-collections.ts (3, 14): Cannot find name 'Package'.
server/methods.ts (1, 24): Cannot find module 'meteor/meteor'.
server/methods.ts (3, 30): Cannot find module 'meteor/check'.
server/publications.ts (1, 24): Cannot find module 'meteor/meteor'.
server/publications.ts (2, 23): Cannot find module 'meteor/mongo'.
server/main.ts (1, 24): Cannot find module 'meteor/meteor'.
server/main.ts (4, 26): Cannot find module 'meteor/accounts-base'.
=> Started MongoDB.
W20161202-01:20:27.141(1)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20161202-01:20:27.271(1)? (STDERR) While this implementation will work correctly, it is known to be
W20161202-01:20:27.271(1)? (STDERR) approximately three times slower than the native implementation.
W20161202-01:20:27.272(1)? (STDERR) In order to use the native implementation instead, run
W20161202-01:20:27.272(1)? (STDERR)
W20161202-01:20:27.272(1)? (STDERR)   meteor npm install --save bcrypt
W20161202-01:20:27.273(1)? (STDERR)
W20161202-01:20:27.274(1)? (STDERR) in the root directory of your application.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.```

So it means that I have some missing modules:
```Cannot find module 'meteor/meteor'
Cannot find module 'meteor/check'
Cannot find module 'meteor/mongo'
Cannot find module 'meteor/accounts-base'```

I have done these to add meteor/accounts-base & meteor/accounts-base
From api folder
```meteor add check
meteor add accounts-base```

From project root
`npm install accounts-base-client-side --save`

But still getting the same output and I don't know what to do with these error messages
```Cannot find module 'meteor/mongo'
Cannot find module 'meteor/meteor'
Cannot find name 'Package'```

**Comment by DAB0mB** [comment]
@DeeM297 Based on your recent comment, it seems as if you have type declarations missing. Try running the following:

    $ npm install meteor-typings --save-dev

**Don't forget to import them as well!** otherwise it won't work...
Declarations are Typescript's way to ensure the right data-types so its compiler can work properly. More information can be found here: https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html 

Please tell if it worked or not :-)

**Comment by DAB0mB** [comment]
In addition, try this solution https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/20#issuecomment-264492599
But I recommend you to first solve the first one so you can be sure what's the cause for your issue.

**Comment by DeeM297** [comment]
@DAB0mB Thanks for your reply.

I've installed the typings. They're already included in the project in the file typing.d.ts in api folder:
```
/// <reference types="meteor-typings" />
/// <reference types="@types/underscore" />
/// <reference types="@types/moment" />
```
https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/blob/master/api/typings.d.ts

It didn't change the output. Having the same messages.

**Comment by DAB0mB** [comment]
@DeeM297 Yea I see, I haven't looked at this repo for quiet a bit now and it changed a little, the typings are not installed correctly. Let me fix that and update it asap and I will let you know when it's done, then we can go further with the issue.

**Comment by DAB0mB** [comment]
@DeeM297 I just updated the tutorial it's on the master branch. Re-clone it, `npm install` it, and run it, tell me if it works for you now. I have no typing errors what so ever.

**Comment by DeeM297** [comment]
Thanks @DAB0mB 

So this is what I have done:
1) Git clone the project

2) On the root project: `meteor npm install`
Output: getting one error `UNMET PEER DEPENDENCY meteor-client-side@1.3.5`
When I try `npm install --save meteor-client-side@1.3.5`, it fails with this message `npm WARN accounts-phone@0.0.1 requires a peer of meteor-client-side@~0.2.3 but none was installed.`
This is resolved by doing this `npm install --save meteor-client-side@~0.2.3`

3) Now in api folder, launching the server with `meteor`
This is the output
```
[[[[[ c:\Ionic\Ionic2CLI-Meteor-WhatsApp\api ]]]]]

=> Started proxy.
=> Started MongoDB.
collections/whatsapp-collections.ts (1, 33): Cannot find module 'meteor-rxjs'.
collections/whatsapp-collections.ts (3, 14): Cannot find name 'Package'.

Unable to resolve some modules:

  "meteor-rxjs" in /c/Ionic/Ionic2CLI-Meteor-WhatsApp/api/collections/whatsapp-collections.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save meteor-rxjs

server/methods.ts (1, 24): Cannot find module 'meteor/meteor'.
server/methods.ts (3, 30): Cannot find module 'meteor/check'.
server/publications.ts (1, 24): Cannot find module 'meteor/meteor'.
server/publications.ts (2, 23): Cannot find module 'meteor/mongo'.
server/main.ts (1, 24): Cannot find module 'meteor/meteor'.
server/main.ts (4, 26): Cannot find module 'meteor/accounts-base'.

Unable to resolve some modules:

  "meteor-rxjs" in /c/Ionic/Ionic2CLI-Meteor-WhatsApp/api/collections/whatsapp-collections.js (os.windows.x86_32)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save meteor-rxjs

W20161203-01:40:56.092(1)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20161203-01:40:56.278(1)? (STDERR) While this implementation will work correctly, it is known to be
W20161203-01:40:56.279(1)? (STDERR) approximately three times slower than the native implementation.
W20161203-01:40:56.280(1)? (STDERR) In order to use the native implementation instead, run
W20161203-01:40:56.281(1)? (STDERR)
W20161203-01:40:56.281(1)? (STDERR)   meteor npm install --save bcrypt
W20161203-01:40:56.283(1)? (STDERR)
W20161203-01:40:56.284(1)? (STDERR) in the root directory of your application.
=> Started your app.

=> App running at: http://localhost:3000/
   Type Control-C twice to stop.
```

I am getting almost the same messages. Am I doing anything wrong with the commands?

**Comment by DAB0mB** [comment]
@DeeM297 For me it runs perfect and it probably has to do something with the fact that your'e using Windows and not a Unix based OS. My suggestion is that the issue occurs because Windows doesn't support a symbolic link operation. We will need to find an alternative. I would have replaced the `node_modules` dir in the `api` dir with a shortcut referencing to the project's root `node_modules` dir (`api/node_modules -> node_modules`). Try that and tell me what happens.

**Comment by DeeM297** [comment]
@DAB0mB I placed the _node_modules_ shortcut from root to the api folder but it had no effect. I'm getting the same message when I run meteor :(

**Comment by mmazloum** [comment]
@DeeM297 based on meteor client side your server should run on port 3000 and your app on port 8100 it seems that your configuration is different when you say : 
App running at: http://localhost:3000/
Running dev server: http://localhost:8100

I used to have the same compilation "errors" but still my apps work, I think the app stills finds the packages after it is built so your signin problem should not come from here ;-)

**Comment by DeeM297** [comment]
I am trying to do the tutorial, step by step. I am on Step 3 at the moment, I had some problem with both meteor and ionic but it's working right now (end of step 3). 

On ionic side, `.config/webpack.config.js` is not compatible with `"@ionic/app-scripts": "0.0.45"`. I tried to figure it out but not working. So, I changed app-scripts to 0.0.37-5 and it is working right now but I am getting this output
```
c:\Ionic\tmp\Ionic2CLI-Meteor-WhatsApp>ionic serve

> ionic-hello-world@ ionic:serve c:\Ionic\tmp\Ionic2CLI-Meteor-WhatsApp
> ionic-app-scripts serve

[13:28:40]  ionic-app-scripts 0.0.37-5
[13:28:40]  watch started ...
[13:28:40]  build dev started ...
[13:28:40]  clean started ...
[13:28:40]  clean finished in 8 ms
[13:28:40]  copy started ...
[13:28:40]  transpile started ...
[13:28:41]  lint started ...
[13:28:45]  transpile finished in 4.47 s
[13:28:45]  webpack started ...
[13:28:45]  copy finished in 4.83 s
[13:28:45]  lint finished in 4.40 s

[at-loader] Using typescript@2.0.6 from typescript and "tsconfig.json" from c:\Ionic\tmp\Ionic2CLI-Meteor-WhatsApp/tsconfig.json

[at-loader] Checking started in a separate process...

[at-loader] Checking finished with 1 errors
[13:29:02]  webpack finished in 17.90 s
[13:29:02]  sass started ...
[13:29:07]  sass finished in 4.82 s
[13:29:07]  build dev finished in 27.23 s
Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:540:16)
    at Object.send (c:\Ionic\tmp\Ionic2CLI-Meteor-WhatsApp\node_modules\awesome-typescript-loader\src\checker\send.ts:24:35)
    at Checker.req (c:\Ionic\tmp\Ionic2CLI-Meteor-WhatsApp\node_modules\awesome-typescript-loader\src\checker\checker.ts:87:21)
    at Checker.emitFile (c:\Ionic\tmp\Ionic2CLI-Meteor-WhatsApp\node_modules\awesome-typescript-loader\src\checker\checker.ts:98:21)
    at transform (c:\Ionic\tmp\Ionic2CLI-Meteor-WhatsApp\node_modules\awesome-typescript-loader\src\index.ts:106:29)
    at transformationFunction (c:\Ionic\tmp\Ionic2CLI-Meteor-WhatsApp\node_modules\awesome-typescript-loader\src\index.ts:57:44)
    at compiler (c:\Ionic\tmp\Ionic2CLI-Meteor-WhatsApp\node_modules\awesome-typescript-loader\src\index.ts:73:30)
    at Object.loader (c:\Ionic\tmp\Ionic2CLI-Meteor-WhatsApp\node_modules\awesome-typescript-loader\src\index.ts:15:18)
    at LOADER_EXECUTION (c:\Ionic\tmp\Ionic2CLI-Meteor-WhatsApp\node_modules\loader-runner\lib\LoaderRunner.js:114:14)
    at runSyncOrAsync (c:\Ionic\tmp\Ionic2CLI-Meteor-WhatsApp\node_modules\loader-runner\lib\LoaderRunner.js:115:4)
[13:29:08]  watch ready in 27.50 s
[13:29:08]  dev server running: http://localhost:8100/
```

On meteor side, in the api folder, this command `meteor npm install --save meteor-node-stubs zone.js meteor-rxjs meteor-typings babel-runtime` is giving me this output `UNMET PEER DEPENDENCY rxjs@^5.0.0-beta.12`. 
This is solved by doing `meteor npm install --save rxjs@5.0.0-beta.12` in the api folder.

Fingers' cross for the next step 4.

**Comment by DeeM297** [comment]
@mmazloum I have tried to launch on port 3000 with `ionic serve -p 3000` but it didn't have any effect.

**Comment by DAB0mB** [comment]
@DeeM297 No no this is not the problem, you run it locally right? You don't run it on a mobile device or some sort? I think if you can find an alternative to a symbolic link on a Windows machine that would be the solution, rather than just creating a shortcut as I suggested in my recent post.

**Comment by DeeM297** [comment]
@DAB0mB Yes I am running this locally with `ionic serve`

I am following the tutorial and things were working up to the end of step 4. I am stuck at the Authentication stage.

**First Issue**
When I did `npm install accounts-phone --save`, I got a dependency error message
``-- UNMET PEER DEPENDENCY meteor-client-side@1.3.5`
By doing `npm install --save meteor-client-side@1.3.5`, I get
`npm WARN accounts-phone@0.0.1 requires a peer of meteor-client-side@~0.2.3 but none was installed.`
So I did `npm install --save meteor-client-side@~0.2.3`
Which means that now **I am running with meteor-client-side@0.2.3**

**Second Issue**
In file _api/server/methods.ts_, I am not able to `import { Profile } from "api/models/whatsapp-models";`, I am getting module not found.

**Third Issue**
In the api folder, `meteor` command shows me this error:
`server/main.ts (14, 26): Property '_options' does not exist on type 'typeof Accounts'.`

**Fourth Issue**
With `ionic serve`, I am getting these two errors
`TypeError: Package['accounts-base'] is undefined`
`GET XHR http://localhost:8100/sockjs/info [HTTP/1.1 404 Not Found 1ms]`

I have pushed my code on github, it shows the changes from Step 4 to Step 5
[Ionic, Client Side](https://github.com/DeeM297/Ionic2CLI-Meteor-WhatsApp/commit/6769e226465bd9694bea19d9c775ae5b1ed0aa95)
[Meteor, Server Side](https://github.com/DeeM297/Ionic2CLI-Meteor-WhatsApp/commit/dffef49c09e4936a72f952b9fca045a0c9ceaad4)

Any ideas on why things are going south at step 5?

**Comment by darkbasic** [comment]
Closing due to inactivity and cleanup after tons of new updates.
Feel free to open a new issue if you are still affected .
