### ISSUE TITLE
spawnSync meteor ENOENT

### ISSUE THREAD

**Issue by galmoc** [Urigo/Ionic2CLI-Meteor-WhatsApp#45]
Hello

I've used Meteor before plugged with Unity but I'm new to ionic 2 and Angular 2 and wanted to thank you for the great tutorial.

When I install `meteor-client-bundler` I then try to run `npm run meteor-client:bundle` after updating 'package.json' but I get this error I can't figure out. Could you please help?

> `Error: spawnSync meteor ENOENT
    at exports._errnoException (util.js:1022:11)
    at spawnSync (child_process.js:461:20)
    at Object.execFileSync (child_process.js:498:13)
    at Object.bundle (C:\Users\hadrien\AppData\Roaming\npm\node_modules\meteor-client-bundler\bundler.js:38:3)
    at Command.<anonymous> (C:\Users\hadrien\AppData\Roaming\npm\node_modules\meteor-client-bundler\cli:37:13)
    at Command.listener (C:\Users\hadrien\AppData\Roaming\npm\node_modules\meteor-client-bundler\node_modules\commander\index.js:301:8)
    at emitTwo (events.js:106:13)
    at Command.emit (events.js:191:7)
    at Command.parseArgs (C:\Users\hadrien\AppData\Roaming\npm\node_modules\meteor-client-bundler\node_modules\commander\index.js:615:12)
    at Command.parse (C:\Users\hadrien\AppData\Roaming\npm\node_modules\meteor-client-bundler\node_modules\commander\index.js:458:21)

> npm ERR! Windows_NT 10.0.14393
> npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "meteor-client:bundle"
> npm ERR! node v6.9.5
> npm ERR! npm  v4.2.0
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! ionic-hello-world@ meteor-client:bundle: `meteor-client bundle`
> npm ERR! Exit status 1`

I attached npm logs as well...

Many thanks in advance,
h

[2017-02-02T10_35_13_342Z-debug.txt](https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/files/747497/2017-02-02T10_35_13_342Z-debug.txt)

**Comment by Slavrix** [comment]
https://github.com/Urigo/meteor-client-bundler/issues/1#issuecomment-276835143

There is a issue relating to this on the bundler's page itself.
its being worked on.

**Comment by Slavrix** [comment]
I just tested the changes and they seem to be working for me now.
get the latest version of the https://github.com/Urigo/meteor-client-bundler and give it another go.

**Comment by galmoc** [comment]
Indeed! Thanks @Slavrix

**Comment by pubkey** [comment]
If you come here from google: This error also occurs if you have not installed the meteor cli.
Test with `meteor --version`
Install with `curl https://install.meteor.com/ | sh`
