### ISSUE TITLE
on latest build: Runtime Error Cannot find module "meteor-client"

### ISSUE THREAD

**Issue by biomassives** [Urigo/Ionic2CLI-Meteor-WhatsApp#54]
Hi Urigo and others who have helped create this great tutorial and app

I'm going round and round trying to meet dependencies with the latest code.

in ~/meteor/Ionic2CLI-Meteor-WhatsApp
dev server running: http://localhost:8100/ 

├── UNMET PEER DEPENDENCY @angular/common@2.2.1
├── UNMET PEER DEPENDENCY @angular/core@2.2.1
├── meteor-rxjs@0.4.7 
├── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12
└── sharp@0.17.2 

npm WARN angular2-google-maps@0.17.0 requires a peer of @angular/common@^2.3.1 but none was installed.
npm WARN angular2-google-maps@0.17.0 requires a peer of @angular/core@^2.3.1 but none was installed.
npm WARN meteor-rxjs@0.4.7 requires a peer of rxjs@^5.0.1 but none was installed.

  meteor npm install --save meteor-rxjs sharp 
                                              
=> Started MongoDB.                           
=> Started your app.                          

=> App running at: http://localhost:3000/

>> on localhost:8181

Runtime Error
Cannot find module "meteor-client"
Stack
Error: Cannot find module "meteor-client"
    at webpackMissingModule (http://localhost:8100/build/main.js:142119:65)
    at Object.<anonymous> (http://localhost:8100/build/main.js:142119:155)
    at __webpack_require__ (http://localhost:8100/build/main.js:20:30)
    at http://localhost:8100/build/main.js:66:18
    at http://localhost:8100/build/main.js:69:10
Ionic Framework: 2.0.0-rc.5
Ionic Native: 2.2.11
Ionic App Scripts: 1.0.0
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 6.9.2
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36

>>so, another attempt at updating node_modules...

Gregs-iMac% rm -rf node_modules && npm install         
npm WARN angular2-google-maps@0.17.0 requires a peer of @angular/common@^2.3.1 but none was installed.
npm WARN angular2-google-maps@0.17.0 requires a peer of @angular/core@^2.3.1 but none was installed.
npm WARN meteor-rxjs@0.4.7 requires a peer of rxjs@^5.0.1 but none was installed.

**Comment by biomassives** [comment]
i think i resolve the rxjs , angular-common, and angular-core dependency issue.. this was my most recent attempt.. ( since :8018 is breaking on meteor-client)

Gregs-iMac% meteor npm install --save meteor-client    
ionic-hello-world@ /Users/greg/dev/meteor/Ionic2CLI-Meteor-WhatsApp
├── UNMET PEER DEPENDENCY @angular/common@2.2.1
├── UNMET PEER DEPENDENCY @angular/core@2.2.1
├─┬ meteor-client@1.3.1 
│ ├── meteor-base64@1.3.0 
│ ├── meteor-blaze@1.5.0 
│ ├── meteor-blaze-tools@1.5.0 
│ ├── meteor-core@1.3.1 
│ ├── meteor-diff-sequence@1.3.1 
│ ├── meteor-ejson-safe@1.3.0 
│ ├── meteor-html-tools@1.5.0 
│ ├── meteor-htmljs@1.5.0 
│ ├── meteor-id-map@1.3.0 
│ ├── meteor-minimongo@1.3.1 
│ ├── meteor-mongo-id@1.3.0 
│ ├── meteor-observe-sequence@1.5.1 
│ ├── meteor-ordered-dict@1.3.0 
│ ├── meteor-random-window-crypto@1.3.1 
│ ├── meteor-reactive-object-map@1.4.6 
│ ├── meteor-reactive-var@1.3.0 
│ ├── meteor-spacebars@1.3.0 
│ ├── meteor-spacebars-compiler@1.3.2 
│ ├── meteor-templating@1.3.0 
│ └── meteor-tracker@1.3.0 
└── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.12

**Comment by biomassives** [comment]
ref:  Gregs-iMac% meteor npm install -g --save meteor-client
/Users/greg/.meteor/packages/meteor-tool/.1.4.2_6.tnur8y++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib
└── meteor-client@1.3.1 

Gregs-iMac% npm run meteor-client:bundle              

> ionic-hello-world@ meteor-client:bundle /Users/greg/dev/meteor/Ionic2CLI-Meteor-WhatsApp
> meteor-client bundle -s api

sh: meteor-client: command not found

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "meteor-client:bundle"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! ionic-hello-world@ meteor-client:bundle: `meteor-client bundle -s api`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the ionic-hello-world@ meteor-client:bundle script 'meteor-client bundle -s api'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ionic-hello-world package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     meteor-client bundle -s api
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ionic-hello-world
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ionic-hello-world
npm ERR! There is likely additional logging output above.

**Comment by gotu** [comment]
According to https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/blob/master/manuals/views/step4.md#preparing-the-meteor-client

you should install "meteor-client-bundler" and use it to build your "meteor-client" bundle

**Comment by darkbasic** [comment]
Closing due to inactivity and cleanup after tons of new updates.
Feel free to open a new issue if you are still affected.
