### ISSUE TITLE
How difficult to add other Meteor authentication like accounts-ui and accounts-password?

### ISSUE THREAD

**Issue by AndyDorman** [Urigo/Ionic2CLI-Meteor-WhatsApp#72]
Love the tutorial and I am up to step 11 with everything working great, but my ultimate application is going to need a more traditional starting point with a "home" page and other authentication options such as password.  I would like to continue using Meteor's account-base, but if I can't easily add password authentication and others (like FB) I may have to start over.

I am not so worried about how to move to a different starting home page, but I suspect that moving to the standard Meteor accounts-ui and accounts-password may not be as simple as `api$ meteor add accounts-ui accounts-password` and then adding the `<login-buttons></login-buttons>` directive to the home page.

Has anyone tried doing this yet?

Thanks for any advice or hints.  I am going to try it and will report back on what happens.

**Comment by gotu** [comment]
I'm using accounts-password instead of accounts-phone..
So basically the meteor project get's
`$ meteor add accounts-password  `
insted of mys:accounts-phone..

And the sign in page with a form for username and password validated the form and uses then:
```
Meteor.loginWithPassword(this.logon.username, this.logon.password, (error: Error) => {
                if (error) {
                    return this.handleLoginError(error);
                } else {
                    this.events.publish('user:auth:login');
                }
            });
```

I didn't try accounts-ui..

**Comment by AndyDorman** [comment]
Thanks gotu.  That was very helpful.
Just to help anyone else that reads this, I really want BOTH SMS and password (and other) authentication.  So here is what I have tried and the results I have had:

I really, really did not want to have to write my own authentication system with login, lost password, change password, etc..So I have tried the following with the results noted below:
1. I added Meteor useraccounts-ionic (which brings in useraccounts-core) and accounts-password.  But this caused Meteor to complain with this error:
```
W20170308-09:38:21.064(-6)? (STDERR) Error: Can't set `forbidClientAccountCreation` more than once
W20170308-09:38:21.065(-6)? (STDERR)     at packages/accounts-base/accounts_common.js:144:17
W20170308-09:38:21.066(-6)? (STDERR)     at Array.forEach (native)
W20170308-09:38:21.066(-6)? (STDERR)     at Function._.each._.forEach (packages/underscore.js:139:11)
W20170308-09:38:21.066(-6)? (STDERR)     at AccountsServer.config (packages/accounts-base/accounts_common.js:141:7)
W20170308-09:38:21.066(-6)? (STDERR)     at AccountsServer.Ap.config (packages/accounts-base/accounts_server.js:1188:53)
W20170308-09:38:21.066(-6)? (STDERR)     at packages/useraccounts_core.js:1123:10
W20170308-09:38:21.066(-6)? (STDERR)     at packages/useraccounts_core.js:1134:4
W20170308-09:38:21.067(-6)? (STDERR)     at packages/useraccounts_core.js:1349:3
W20170308-09:38:21.067(-6)? (STDERR)     at /home/adorman/programming/comehome/api/.meteor/local/build/programs/server/boot.js:303:34
W20170308-09:38:21.067(-6)? (STDERR)     at Array.forEach (native)

```
I finally got past this error by removing mys:accounts-phone.
Then I had two problems trying to use useraccounts-ionic and useraccounts-unstyled which I never figured out:
1. I could not figure out how to import AccountsTemplates anywhere so I could safely configure useraccounts-ionic as specified here (https://atmospherejs.com/useraccounts/ionic).  Nowhere that I could find does anyone say which accounts package exports AccountsTemplates. Very frustrating!
2. So I gave up trying to set AccountsTemplates.config, but then I could never figure out how to call {{< atForm}} on my home page.  Every time I tried it ionic would explode in my face complaining about it (it was late at night and I never copied the error message.  I will be happy to recreate the problem if anyone is interested in the error.

I suspect part of the problem could be that Meteor-useraccounts wants either iron-router or flow-router (though the gude says otherwise) and the latest Meteor-Angular2-Ionic2 as described in the Whatsapp clone tutorial doesn't need or use either one.  But I could be totally wrong about that.

So now I am also giving up on Meteor useraccounts system because no matter what they claim in the guide, I have been unable to make it work or find ANY source code examples of it actually working. :-(

**Comment by gotu** [comment]
Did you try https://github.com/Urigo/angular2-meteor-accounts-ui for accounts-ui?

**Comment by AndyDorman** [comment]
On 03/13/2017 11:19 AM, gotu wrote:
> Did you try https://github.com/Urigo/angular2-meteor-accounts-ui for
> accounts-ui?
>
>

Thank you.

I feel rather silly for not thinking of that.  I will try it and report 
back.

I looked at the demo at

https://github.com/Urigo/angular2-meteor-accounts-ui

If I read it correctly I should use "<login-buttons></login-buttons>" in 
my template where I need the login button to be, correct?

Andy

**Comment by AndyDorman** [comment]
On 03/13/2017 09:32 PM, Andy Dorman wrote:
> On 03/13/2017 11:19 AM, gotu wrote:
>> Did you try https://github.com/Urigo/angular2-meteor-accounts-ui for
>> accounts-ui?
>>
>>
>
> Thank you.
>
> I feel rather silly for not thinking of that.  I will try it and report
> back.
>
> I looked at the demo at
>
> https://github.com/Urigo/angular2-meteor-accounts-ui
>
> If I read it correctly I should use "<login-buttons></login-buttons>" in
> my template where I need the login button to be, correct?
>
> Andy

FWIW I started to try angular2-meteor-accounts-ui and ran into a snag 
that definitely shows how new I am to npm and meteor.

I do not know how to add the package to the whatsapp structure with 
meteor only on the server in the /api directory.

Running "/api$ meteor npm install --save angular2-meteor-accounts-ui" 
runs into a missing "api/package.json" file.  So even though it seems to 
install angular2-meteor-accounts-ui, it does not show up on the client 
side when I run "$ npm run meteor-client:bundle".

I also tried "/api$ meteor npm install angular2-meteor-accounts-ui" with 
similar results.

Any suggestions (aside from learning about the meteor and npm 
installation processes ;-)?

Thanks

-- 
Andy

**Comment by pizzetto** [comment]
@AndyDorman did you succeded? 

I'm facing the same problem. I may think to draw a custom login/register/etc view built upon the accounts-password, do you think that works?

**Comment by pizzetto** [comment]
I wonder if @gotu has built his own authentication interface. Could you please explain how did you do this?

**Comment by AndyDorman** [comment]
On 04/21/2017 06:58 PM, pizzetto wrote:
> @AndyDorman <https://github.com/AndyDorman> did you succeded?
>
> I'm facing the same problem. I may think to draw a custom
> login/register/etc view built upon the accounts-password, do you think
> that works?
>

I finally gave up on adding angular2-meteor-accounts-ui and just decided 
to add accounts-password alongside mys:accounts-phone and add my own 
login forms and pages.

It wasn't too difficult to get it working, but I still have a lot of 
rough edges...for example I still need to make sure an unauthenticated 
user can ONLY see the public pages and need to add a "forgot password" 
process.

The toughest part was setting up a different authentication flow from 
what the tutorial has based solely on SMS auth. Here is the flow I use 
now (new pages are marked *):

Home*
   - About*
   - Signup* (a form page that creates an account and logs the user in)
   - SMS auth (current tutorial start page)
     -- Verification page
       --- Profile page
         ---- Tabs page (I did not remove it in step 2.6 and used it for 
the base home page for authenticated users instead of the chats page)
   - Password auth* (an Alert box with a two-field auth form)
         ---- Tabs page

So the number of changes I have made go way, way past just adding 
password auth, but if you follow the examples in the tutorial SMS auth 
it isn't difficult.

I do not want to make the tutorial more complicated by submitting a pull 
request for everything I am doing (plus I am just starting in js and I 
am sure I am doing some things wrong :-), but perhaps I can work on a PR 
that JUST adds conventional account signup and password authentication 
alongside the SMS auth.  I will try to find the time for that in the 
next couple of weeks.

-- 
Andy Dorman

**Comment by pizzetto** [comment]
As well as you, I'm just starting to code in js and meteor.
So we have three options right?

1. useraccounts-ionic (I'm reading the guide here https://github.com/meteor-useraccounts/core/blob/master/Guide.md#available-versions) but it seems to be made for angular1
2. angular2-meteor-accounts-ui but I cannot find any guide about it
3. accounts-password alongside mys:accounts-phone as you did. If I was skilled on meteor and js in general I'd follow this way. I love the way you can download and drop in your project plugins that works out of the box, as you do typically in js. This leave me time to think about more specific features.

I will try to follow on of these 3 ways, and I'll let you know what comes out!

And I'm curious to have a look to your project, is that public?

**Comment by AndyDorman** [comment]
I think you are correct that those are our three options.

I tried to use useraccounts:ionic but as you said, it is old (with 
flow/iron router) and I did not want to add old packages that I was not 
going to use in the rest of the project.

I was unable to get angular2-meteor-accounts-ui to work as I described 
in this ticket.

So I am doing my own and it is not hard.  I added a very simple "home" 
page that looks a lot like the tutorial "chats" page (but without the 
complexity of listing chats) with an "options" button calls a 
"public-options" page that I copied from the tutorial "chat-options". 
The Public-options page just lists the login options (SMS log, pwd 
login, join, and an About page).  From there the SMS login is exactly 
like the tutorial. The login page is a simple modal with the 
username/pwd form that calls the "Meteor.loginWithPassword" code Gotu 
listed in this ticket. If you Google "Meteor.loginWithPassword" you can 
find other examples too.

As for my project, it is not public yet (we have a private git 
repository).  I am making a lot of mistakes right now and would feel 
very bad if someone tried to use my code as an example of how to do 
something.

However, I am trying to organize the parts that are small changes so I 
can submit them as a Pull Request to expand the tutorial.  I am sure 
Urigo and Dotan Simha can make sure I do not submit anything that will 
cause trouble.  ;-)

Andy

**Comment by pizzetto** [comment]
Yeah, you're right.
I started with useraccounts:ionic, but I stumbled upon the same issue as you did, the same!

And yeah, really, how do you find a documentation if it is missing from a project readme/home page? 
It's not easy to find the source code of the package, or at least, it is for me. 
I can't even succeed to import useraccounts:ionic...how you do that?? I got an error of package not found even if it's installed.

I think I will try your same strategy, in the meantime thanks Andy :)

**Comment by kevinrfx8** [comment]
To handle google and facebook auth, you could use an external dependency like https://www.npmjs.com/package/angular2-social-login or the ionic one https://ionicframework.com/docs/native/facebook/, just to get the access token and after that, send it through a method like 
`Meteor.methods({
    'getAccessTokenWithFacebookToken': function (accessToken) {
        this.unblock();
        try {
            const appInfo = HTTP.call('GET', 'https://graph.facebook.com/v2.9/app?access_token=' + accessToken);
            //Do something
            if (appInfo.data.id == Settings.services.facebook.appId) {
                const userInfo = HTTP.call('GET', 'https://graph.facebook.com/v2.9/me?fields=id,name,email&access_token=' + accessToken);
                serviceData = {
                    id: userInfo.data.id,
                    accessToken: accessToken,
                    email: userInfo.data.email
                };
                options = {
                    profile: {
                        name: userInfo.data.name
                    }
                };
                var user = Accounts.updateOrCreateUserFromExternalService('facebook', serviceData, options);
                var stampedLoginToken = {
                    token: Random.secret(),
                    when: new Date
                };
                console.log(user);
                Accounts._insertLoginToken(user.userId, stampedLoginToken);
                console.log(stampedLoginToken);
                return  stampedLoginToken.token;
            }
            else {
                throw new Meteor.Error(500, "Method parameters error", { error:"App id from token " });
            }
        } catch (e) {
            // Got a network error, timeout, or HTTP error in the 400 or 500 range.
            throw e;
        }
    }
});`

That will validate the access token, create a user if not exists, and returns a token to log in into your app, 
and finally use that token to log with:
`Meteor.loginWithToken(res, function (err, res) {
              loading.dismiss();
              if (!err) {
                console.log(Meteor.userId())
                component.navController.setRoot(HomePage);
                
              }
              else {
                console.log(err);
                component.error=err; 
                component.changeDetectorRef.detectChanges();
              }
            });`

**Comment by darkbasic** [comment]
Look [here](https://github.com/Urigo/Ionic2CLI-Meteor-WhatsApp/issues/92) if you need help with ```accounts-facebook```.
